### PR TITLE
feat(checkbox): change component name from `PCheckBox` to `PCheckbox`

### PR DESCRIPTION
**Pull request by yuda110**
### To Reviewers
- [ ] Skipping review is not a problem (```style```, ```chore``` ONLY)
- [x] Not that difficult

### Type of Change
- [x] New feature
- [ ] Bug fixes
- [ ] Feature improvement
  - [ ] These changes require a usage change
- [x] Others (performance improvement, refactoring, CI/CD, etc.)

### Checklist
- [ ] Updated Storybook documents for component
- [ ] Wrote test codes for composable, utils and etc.
- [ ] Tested with console(if usages are changed) 

### Description
- change component name from `PCheckBox` to `PCheckbox`

### CODE REVIEW

**Review by song2kim — APPROVED** [review]
LGTM~~~

**Review by WANZARGEN — APPROVED** [review]
goood

**Review by sulmoJ — APPROVED** [review]
Goood!

**Pull request merged**
