### PR TITLE
fix(p-tag): fix side effect in default slot

### PR DESCRIPTION
**Pull request by piggggggggy**
### To Reviewers
- [ ] Skipping review is not a problem (```style```, ```chore``` ONLY)
- [x] Not that difficult

### Type of Change
- [ ] New feature
- [x] Bug fixes
- [ ] Feature improvement
  - [ ] These changes require a usage change
- [ ] Others (performance improvement, refactoring, CI/CD, etc.)

### Checklist
- [ ] Updated Storybook documents
- [ ] Tested with console

### Description
- move default slot to tag-contents span for handling side effect

### CODE REVIEW

**Review by yuda110 — APPROVED** [review]
Nice

**Review by sulmoJ — APPROVED** [review]
LG T M!

**Review by WANZARGEN — APPROVED** [review]
LGTM! Plz check in console (with link) when u change the spec of the component later~!

**Pull request merged**
